---
title: "projectDataScience"
author: "GIventheo"
date: "2022-11-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('Rstem', repos = "http://www.omegahat.net/R")
```

## Load All library

```{r Load all library}

library(openssl)
library(httpuv)
library(rtweet)
library(SnowballC)
library(httr)
#library(twitteR)
#library(Rstem)
library(textdata)
library(purrr)
library(tm)
library(NLP)
library(SentimentAnalysis)
library(RColorBrewer)
library(wordcloud)
#library(sentiment)
#library(foo)
library(tidyverse) 
library(tidytext)
library(e1071)
library(caret)
library(syuzhet)
library(gmodels)
library(plyr)
library(plotly)
library(DT)
library(sass)

```

## Load Data 

```{r load data from API}
## store api keys (these are fake example values; replace with your own keys)
api_key <- "FBox1hjtTDLO3VZvyKWIZx77j"
api_secret_key <- "b3oOc7sGKHrzCdlHjFP8L6U5zWOdhSiEv3g3TJAfwQ02EV6IW5"
bearer_token <- "AAAAAAAAAAAAAAAAAAAAAF4YjgEAAAAADwzHHipo40WWiP%2F7NYjSaRvL5Gk%3DmLyBXX31ggRKxdEYkNmIid8uEKkzKiQ951aO1lJgE1qvzBC3JS"
clientId <- "MVoyLWVTMEVrWTd6OFUzTGxqbVI6MTpjaQ"
clientSecret <- "URnCd6sUHe4nieKbfnQ1xRJUwmhNOnfCLvXN7RioBY9w07_nPa"
accessToken <- "1592089064374534145-6hpvtXEwCUBMK7wbZCIXaRXTlarEWc"
accessSecret <- "h35r7DP0dR4AcUwBQqUXE5diaPTDkY7TEm4s41cT9X3xp"

token = create_token(
  app = "sentimentAnalysisBooster",
  consumer_key = api_key,
  consumer_secret = api_secret_key,
  access_token = accessToken,
  access_secret = accessSecret,
  set_renv = TRUE
)

auth_save(token, "tweetAccess")
auth_as("tweetAccess")
auth_sitrep()

```

## Search_tweets of Booster Vaccine

```{r Search Tweets}
dataVaksinCovid <- search_tweets('#vaksincovid19', n=500, include_rts=FALSE)
dataVaksinBooster <- search_tweets('#vaksinbooster', n=500, include_rts=FALSE)
dataVaksin <- search_tweets('#vaksin', n=500, include_rts=FALSE)
dataBooster <- search_tweets('#booster', n=500, include_rts=FALSE)

#dataTweets <- sapply(dataTweet, function(x) x$getText())
```

```{r}
data <- rbind(dataVaksinCovid, dataVaksin, dataVaksinBooster, dataBooster)
data <- data %>% select(full_text)
```


## Cleaning Data

```{r}
data1 <-  Corpus(VectorSource(data$full_text))
removeLink <- function(d) gsub("http[^[:space:]]*","",d)
dataClean <- tm_map(data1, removeLink)
removenl <- function(d) gsub("\n"," ",d)
dataClean <- tm_map(dataClean, removenl)
removeComma <- function(d) gsub(",","",d)
dataClean <- tm_map(dataClean, removeComma)
removeTitik2 <- function(d) gsub(":","",d)
dataClean <- tm_map(dataClean, removeTitik2)
removeTitikKoma <- function(d) gsub(";","",d)
dataClean <- tm_map(dataClean, removeTitikKoma)
removeAmp <- function(d) gsub("&amp","",d)
dataClean <- tm_map(dataClean, removeAmp)
removeun <- function(d) gsub("@\\w+","",d)
dataClean <- tm_map(dataClean, removeun)
remove.all <- function(d) gsub("[^[:alpha:][:space:]]","",d)
dataClean <- tm_map(dataClean, remove.all)
dataClean <- tm_map(dataClean, removePunctuation)
dataClean <- tm_map(dataClean, tolower)
df <- data.frame(text=unlist(sapply(dataClean,'[')),stringAsFactors=F)
write.csv(df,file="dataTwitterClean.csv")

```


```{r}
data$stripped_text1 <- gsub("http\\S+","",data$full_text)
data <- data %>% 
  select(stripped_text1) %>% 
  unnest_tokens(word, stripped_text1)
```

```{r}
cleanedData <- data %>%
  anti_join(stop_words)
```

## Split data to training and test
```{r Split data}
dataChar <- as.character(df$text)
sentiment <- get_nrc_sentiment(dataChar)
mergeData <- cbind(df$text,sentiment)
par(mar=rep(3,4))

```

## Classifier and Predict 
```{r Classifier and Predict}
```

## Plotting the data into graph
```{r ggplot and plotly}

```

## Visualize data with shiny to website
```{r shiny web framework}
# UI 
ui <- fluidPage(
  title = "Air Quality",
  headerPanel("Air Quality of Kota Bandung"),
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "station",
                  label =  "Station",
                  choices = option_station,
                  multiple = TRUE,
                  selected = option_station[[1]]),
      selectInput(inputId = "parameter",
                  label = "Parameter",
                  choices = option_parameter,
                  selected = "03"),
      textInput(inputId = "parameter_label",
                label = "Label for parameter",
                value = ""),
      textInput( inputId = "plot_title",
                 label = "Title of Plot",
                 value = ""),
      dateRangeInput( inputId = "date",
                      label = "Date of Graphics",
                      start = "2017-01-01",
                      end = "2017-03-30",
      ),
    ),
    mainPanel(
      plotlyOutput(outputId = "aq_plot")
     
    )
  )
)

# Backend
server <- function(input, output, session) {
  
  aq_plot <- reactive({
    mulai <- format(input$date[[1]])
    akhir <- format(input$date[[2]])
    
    udara_bandung %>%
      filter(station %in% input$station) %>%
      filter(day >= mulai & day <= akhir) %>%
      ggplot(aes_string(x = "day", y = input$parameter, colour = "station")) +
      geom_line() +
      scale_x_date(date_breaks = "1 weeks") +
      labs(
        x = "",
        y = ifelse(input$parameter_label == "", input$parameter, input$parameter_label),
        colour = "Station",
        title = input$plot_title
      ) +
      theme_light()
  })
  

  
  output$aq_plot <- renderPlotly({
    ggplotly(aq_plot())
  })
  

}
```




